name: CI with unit and integration tests
on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches-ignore:
      - main
      - master

jobs:
  build_test:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots compile -Dartifact_version=test

  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: [ build_test ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Verify unit test with Maven
        run: mvn --batch-mode test -Dartifact_version=test > report.txt
      - name: Downloading result in artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit test report
          path: report.txt

  continuous_test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: [ build_test ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Verify integration test with Maven
        run: mvn --batch-mode verify -Dartifact_version=test > report.txt
      - name: Downloading result in artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Continuous test report
          path: report.txt
