name: CI
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  build_test:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache maven packages
        uses: action/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Build with Maven
        run: mvn --batch-mode compile

  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Verify unit test with Maven
        run: mvn --batch-mode test > report.txt

      - name: Downloading result in artifact
        uses: actions/upload-artifact@v2
        with:
          name: Unit test report
          path: report.txt

  continuous_test:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Verify continuous test with Maven
        run: mvn --batch-mode verify > report.txt

      - name: Downloading result in artifact
        uses: actions/upload-artifact@v2
        with:
          name: Continuous test report
          path: report.txt
